package GUI;

import controllers.Buah;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class UpBuah extends javax.swing.JFrame {
    Buah B1;
    int id;

    public UpBuah(int id) throws ClassNotFoundException, SQLException {
        B1 = new Buah();
        this.id = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FormBuah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FormJenis = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FormHarga = new javax.swing.JTextField();
        UpData = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Update Data");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 20, 130, 26);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Insert Buah");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 80, 100, 20);

        FormBuah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormBuahActionPerformed(evt);
            }
        });
        getContentPane().add(FormBuah);
        FormBuah.setBounds(160, 78, 113, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Insert Jenis");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 120, 73, 20);

        FormJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormJenisActionPerformed(evt);
            }
        });
        getContentPane().add(FormJenis);
        FormJenis.setBounds(160, 118, 113, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Insert Harga");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 160, 90, 20);
        getContentPane().add(FormHarga);
        FormHarga.setBounds(160, 158, 113, 22);

        UpData.setBackground(new java.awt.Color(204, 204, 204));
        UpData.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        UpData.setForeground(new java.awt.Color(102, 102, 102));
        UpData.setText("Update");
        UpData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpDataMouseClicked(evt);
            }
        });
        UpData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpDataActionPerformed(evt);
            }
        });
        getContentPane().add(UpData);
        UpData.setBounds(70, 230, 110, 26);

        Cancel.setBackground(new java.awt.Color(204, 204, 204));
        Cancel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Cancel.setForeground(new java.awt.Color(102, 102, 102));
        Cancel.setText("Cancel");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(240, 230, 90, 26);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/update.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FormJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormJenisActionPerformed

    private void FormBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormBuahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormBuahActionPerformed

    private void UpDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpDataActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelActionPerformed

    private void UpDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpDataMouseClicked
        try {    
            String hb = FormBuah.getText();
            String jb = FormJenis.getText();
            String kb = FormHarga.getText();
           

            B1.updatebuah(id, hb, jb, kb);
            
            JOptionPane.showMessageDialog(null, "UBAH DATA BERHASIL");

            new DataBuah().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "UBAH DATA GAGAL");
            try {
                new UpBuah(id).setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(UpBuah.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(UpBuah.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
        this.dispose();
    }//GEN-LAST:event_UpDataMouseClicked

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        try {
            DataBuah m1 = new DataBuah();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        try {
            new DataBuah().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpBuah.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UpBuah.class.getName()).log(Level.SEVERE, null, ex);
        }                                                                     

    }//GEN-LAST:event_CancelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField FormBuah;
    private javax.swing.JTextField FormHarga;
    private javax.swing.JTextField FormJenis;
    private javax.swing.JButton UpData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
